$$
  In this erroneous grace program an array is declared to have size a
  non-positive number.

  Array 'intArray' is declared to have size 0, which is not possible.
$$

fun main() : nothing
  var intArray : int[0];
  var i : int;

  fun isSorted(ref a : int[0]) : int
    var i, result : int;
  { $ isSorted
    i <- 0;
    result <- 1;
    while i < 9 and result = 1 do {
      if a[i] > a[i + 1] then result <- 0;
      i <- i + 1;
    }
    return result;
  } $ isSorted

{ $ main
  i <- 0;
  while i < 10 do {
    intArray[i] <- i;
    i <- i + 1;
  }
  writeString("There should be an error already.\n");
} $ main
